To change
GoEntry/halls_app pull request #5
Opened 2024-11-07 12:13 UTC by brigme

Добавили всякого

2024-11-07 12:20 UTC, GoEntry reviewed
Cool!

2024-11-07 12:32 UTC, GoEntry approved these changes
Cool!

2024-11-07 13:02 UTC, Laggon requested changes
Добавить планируемые задачи в описание PR или создать их в Issues

2024-11-07 13:02 UTC, Laggon commented on README.MD
> +группа ЭУ-210
В итоговом варианте отображается близко (например добавить пустую строку)

2024-11-07 13:02 UTC, Laggon commented on README.MD
> +- https://github.com/GoEntry/halls_app/blob/main/ТЗ.md
Нужно указать относительную ссылку

2024-11-07 13:02 UTC, Laggon commented on README.MD
> +---
Добавление минимального приложение выполняется в следующем спринте и соответственно документация к нему

2024-11-07 13:06 UTC, Laggon commented
Убрать в README.md первый заголовок (README)

2024-11-21 11:09 UTC, Laggon requested changes
Убрать номера в названиях задач

Описать подробнее задачи

2024-11-21 12:00 UTC, GoEntry approved these changes

2024-11-21 12:08 UTC, DmitriyManushin approved these changes

2024-11-21 12:10 UTC, DmitriyManushin approved these changes

2024-11-21 12:34 UTC, Laggon approved these changes

2024-11-21 12:40 UTC, merged